---
services:
  eng-ai-agents:
    build:
      context: "."
      dockerfile: ./docker/Dockerfile.dev.gpu
    image: eng-ai-agents
    shm_size: "4gb" # Shared memory size
    user: vscode
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - eng-ai-agents-net

networks:
  eng-ai-agents-net:
    driver: bridge

volumes:
  minio_data:
  rye-cache:
