services:
  app:
    build:
      dockerfile: ./Dockerfile
    image: project_app
    shm_size: "4gb"
    user: vscode

    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - local
    volumes:
      - .:/workspaces/app:cached

  mongo:
    image: mongo:latest
    container_name: "project_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "tu34"
      MONGO_INITDB_ROOT_PASSWORD: "123"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "project_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always

volumes:
  mongo_data:
  qdrant_data:

networks:
  local:
    driver: bridge
